
services:
  app:
    image: node:22-bullseye
    command: sleep infinity
    # network_mode: service:db
    volumes:
      - ../:/workspaces/app:cached
    env_file:
      - ../.vercel.env
  
